
# Sharing and editing is allowed, but leave these first lines alone.
# Source: https://github.com/huizebruin/huizebruin-projecten
# Source File: https://github.com/huizebruin/huizebruin-projecten
# © https://huizebruin.nl
substitutions:
  device_description: ${name} made by Huizebruin projects version ${project_version}.
  project_version: "1.0.4" 
  date: "03-05-2025"

preferences:
  flash_write_interval: 120min

improv_serial:

wifi:
  ap:

api:

web_server:
  port: 80
  version: 3

captive_portal:

# ⬇ Enable logging ⬇ #
logger:
  level: INFO
  # esp8266_store_log_strings_in_flash: false

ota:
  - platform: esphome
    id: ota_esphome
  # - platform: http_request
  #   id: ota_http_request

http_request:
  verify_ssl: false

time:
  - platform: homeassistant
    id: time_homeassistant
    on_time_sync:
      - component.update: ${name}_uptime_timestamp

# https://esphome.io/components/safe_mode  need for ESPHome v2024.6.x
safe_mode:

sensor:
#------------------------#  sensoren #------------------------#
  - platform: uptime
    id: ${name}_uptime

  - platform: template
    id: ${name}_uptime_timestamp
    name: "${name} online sinds"
    device_class: "timestamp"
    accuracy_decimals: 0
    update_interval: never
    icon: 'mdi:clock-start'
    entity_category: diagnostic
    lambda: |-
      static float timestamp = (
        id(time_homeassistant).utcnow().timestamp - id(${name}_uptime).state
      );
      return timestamp;

# ⬇ version connection information sensors for in ha ⬇ #
  # WiFi signal
  - platform: wifi_signal
    name: "${name} - WiFi Signal"
    update_interval: 120s

text_sensor:
  - platform: template
    name: "tool versie"
    id: ${name}_versie
    icon: 'mdi:alpha-v-circle-outline'
    update_interval: 6h
    entity_category: diagnostic
    lambda: |-
      return {"${project_version}"};

  - platform: wifi_info
    ip_address:
      name: "${name} IP-adres"
      id: ${name}_ip_adres
      icon: mdi:ip-network

    mac_address:
      name: "${name} Mac-adres"
      id: ${name}_mac_adres
      icon: mdi:folder-key-network-outline

#  restart button  #
button:
  - platform: restart
    name: "${name} Restart device"
    entity_category: diagnostic

# Factory Reset Switch from ESPHome v2022.09
  - platform: factory_reset
    name: "Restart with Factory Default Settings"
    entity_category: diagnostic
    disabled_by_default: True

  # safe mode button
  - platform: safe_mode
    name: "Safe Mode"
    entity_category: diagnostic
    disabled_by_default: True

  # - platform: template
  #   id: check_for_update_button
  #   name: Check for firmware update
  #   device_class: update
  #   on_press:
  #     then:
  #       - component.update: update_http_request
