# Delen en bewerken mag maar laat deze eerste regels staan.
# Bron : https://www.huizebruin.nl
# Bron File : https://github.com/huizebruin/huizebruin-projects
# © Huizebruin.nl
# UART Configuration for HLK-LD2410C
uart:
  id: ld2410_uart
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

# HLK-LD2410C Configuration
ld2410:
  uart_id: ld2410_uart
  throttle: 1000ms

# ----------- #
### SENSORS ###
sensor:
  - platform: ld2410
    moving_distance:
      name: "mmWave Moving Distance"
    still_distance:
      name: "mmWave Still Distance"
    moving_energy:
      name: "mmWave Move Energy"
    still_energy:
      name: "mmWave Still Energy"
    detection_distance:
      name: "mmWave Detection Distance"
      id: mmwave_detection_distance
    light:
      name: "mmWave Lightlevel"
      disabled_by_default: true
    g0:
      move_energy:
        name: "mmWave G0 move energy"
        disabled_by_default: true
      still_energy:
        name: "mmWave G0 still energy"
        disabled_by_default: true
    g1:
      move_energy:
        name: "mmWave G1 move energy"
        disabled_by_default: true
      still_energy:
        name: "mmWave G1 still energy"
        disabled_by_default: true
    g2:
      move_energy:
        name: "mmWave G2 move energy"
        disabled_by_default: true
      still_energy:
        name: "mmWave G2 still energy"
        disabled_by_default: true
    g3:
      move_energy:
        name: "mmWave G3 move energy"
        disabled_by_default: true
      still_energy:
        name: "mmWave G3 still energy"
        disabled_by_default: true
    g4:
      move_energy:
        name: "mmWave G4 move energy"
        disabled_by_default: true
      still_energy:
        name: "mmWave G4 still energy"
        disabled_by_default: true
    g5:
      move_energy:
        name: "mmWave G5 move energy"
        disabled_by_default: true
      still_energy:
        name: "mmWave G5 still energy"
        disabled_by_default: true
    g6:
      move_energy:
        name: "mmWave G6 move energy"
        disabled_by_default: true
      still_energy:
        name: "mmWave G6 still energy"
        disabled_by_default: true
    g7:
      move_energy:
        name: "mmWave G7 move energy"
        disabled_by_default: true
      still_energy:
        name: "mmWave G7 still energy"
        disabled_by_default: true
    g8:
      move_energy:
        name: "mmWave G8 move energy"
        disabled_by_default: true
      still_energy:
        name: "mmWave G8 still energy"
        disabled_by_default: true


# ------------------ #
### BINARY SENSORS ###
binary_sensor:
  - platform: ld2410
    has_target:
      name: "mmWave Presence"
      id: mmwave_presence
    has_moving_target:
      name: "mmWave Moving Target"
    has_still_target:
      name: "mmWave Still Target"

# Zones
  - platform: template
    name: "mmWave Zone 1"
    device_class: occupancy
    icon: mdi:motion-sensor
    lambda: |-
      if ((id(mmwave_presence).state) && (id(mmwave_detection_distance).state < id(mmwave_z1_end).state)) {
        return true;
      } else {
        return false;
      }
  - platform: template
    name: "mmWave Zone 2"
    device_class: occupancy
    icon: mdi:motion-sensor
    lambda: |-
      if ((id(mmwave_presence).state) && ((id(mmwave_z1_end).state < id(mmwave_detection_distance).state) && (id(mmwave_detection_distance).state < id(mmwave_z2_end).state))) {
        return true;
      } else {
        return false;
      }
  - platform: template
    name: "mmWave Zone 3"
    device_class: occupancy
    icon: mdi:motion-sensor
    lambda: |-
      if ((id(mmwave_presence).state) && ((id(mmwave_z2_end).state < id(mmwave_detection_distance).state) && (id(mmwave_detection_distance).state < id(mmwave_z3_end).state))) {
        return true;
      } else {
        return false;
      }


# ------------ #
### SWITCHES ###
switch:
  - platform: ld2410
    engineering_mode:
      name: "mmWave Engineering mode"
      disabled_by_default: true
    bluetooth:
      name: "mmWave Bluetooth"
      disabled_by_default: true


# ----------- #
### NUMBERS ###
number:
  - platform: ld2410
    timeout:
      name: "mmWave Timeout"
    light_threshold:
      name: "mmWave Light threshold"
    max_move_distance_gate:
      name: "mmWave Max. move distance gate"
      disabled_by_default: true
    max_still_distance_gate:
      name: "mmWave Max. still distance gate"
      disabled_by_default: true
    g0:
      move_threshold:
        name: "mmWave G0 move threshold"
        disabled_by_default: true
      still_threshold:
        name: "mmWave G0 still threshold"
        disabled_by_default: true
    g1:
      move_threshold:
        name: "mmWave G1 move threshold"
        disabled_by_default: true
      still_threshold:
        name: "mmWave G1 still threshold"
        disabled_by_default: true
    g2:
      move_threshold:
        name: "mmWave G2 move threshold"
        disabled_by_default: true
      still_threshold:
        name: "mmWave G2 still threshold"
        disabled_by_default: true
    g3:
      move_threshold:
        name: "mmWave G3 move threshold"
        disabled_by_default: true
      still_threshold:
        name: "mmWave G3 still threshold"
        disabled_by_default: true
    g4:
      move_threshold:
        name: "mmWave G4 move threshold"
        disabled_by_default: true
      still_threshold:
        name: "mmWave G4 still threshold"
        disabled_by_default: true
    g5:
      move_threshold:
        name: "mmWave G5 move threshold"
        disabled_by_default: true
      still_threshold:
        name: "mmWave G5 still threshold"
        disabled_by_default: true
    g6:
      move_threshold:
        name: "mmWave G6 move threshold"
        disabled_by_default: true
      still_threshold:
        name: "mmWave G6 still threshold"
        disabled_by_default: true
    g7:
      move_threshold:
        name: "mmWave G7 move threshold"
        disabled_by_default: true
      still_threshold:
        name: "mmWave G7 still threshold"
        disabled_by_default: true
    g8:
      move_threshold:
        name: "mmWave G8 move threshold"
        disabled_by_default: true
      still_threshold:
        name: "mmWave G8 still threshold"
        disabled_by_default: true

# Setting ending of zone 1 occupancy
  - platform: template
    name: "mmWave End Zone 1"
    id: mmwave_z1_end
    unit_of_measurement: "cm"
    min_value: 0
    max_value: 600
    step: 1
    mode: box
    update_interval: never
    optimistic: true
    restore_value: true
    initial_value: 0
    icon: "mdi:arrow-collapse-right"
    entity_category: CONFIG

# Setting ending of zone 2 occupancy
  - platform: template
    name: "mmWave End Zone 2"
    id: mmwave_z2_end
    unit_of_measurement: "cm"
    min_value: 0
    max_value: 600
    step: 1
    mode: box
    update_interval: never
    optimistic: true
    restore_value: true
    initial_value: 0
    icon: "mdi:arrow-collapse-right"
    entity_category: CONFIG

# Setting ending of zone 3 occupancy
  - platform: template
    name: "mmWave End Zone 3"
    id: mmwave_z3_end
    unit_of_measurement: "cm"
    min_value: 0
    max_value: 600
    step: 1
    mode: box
    update_interval: never
    optimistic: true
    restore_value: true
    initial_value: 0
    icon: "mdi:arrow-collapse-right"
    entity_category: CONFIG


# ------------- #
### SELECTORS ###
select:
  - platform: ld2410
    distance_resolution:
      name: "mmWave Distance resolution"
      disabled_by_default: true  