site_name: Huizebruin-projecten
docs_dir: source
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - toc.integrate
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.action.edit
  palette:
    - schema: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  logo: images/favicon-96x96.png
  favicon: images/favicon.ico
extra:
  generator: false
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
nav:
  - 'index.md'
  - 'flashing.html'
  - 'Contributing':
      - 'contributing/index.md'
  - 'Tutorials':
      - 'community/index.md'
repo_url: https://github.com/huizebruin/Huizebruin-projecten
edit_uri: blob/master/docs/source/
