# Delen en bewerken mag maar laat deze eerste regels staan.
# Bron : https://www.huizebruin.nl
# Bron File : https://github.com/huizebruin/huizebruin-projects
# © Huizebruin.nl
substitutions:
  device_name: "vindriktning"
  name: "vindriktning"  
  
esphome:
  name: '${device_name}'
  name_add_mac_suffix: true
  comment: '${device_description}'
  project:
    name: "huizebruin-projecten.${device_name}"
    version: "${project_version}"
  min_version: 2024.12.0

esp8266:
  board:  d1_mini

logger:
  level: INFO

dashboard_import:
  package_import_url: github://huizebruin/huizebruin-projecten/esphome/vindriktning.yaml

packages:
  remote_package:
    url: https://github.com/huizebruin/huizebruin-projecten
    ref: main
    files:
      - esphome/package/vindriktning.yaml
      - esphome/package/basis_settings.yaml
    refresh: 0d