---
# vindriktning 
#
# a simple ESPHome integration to make an vindriktning 
# © Huizebruin.nl
#
substitutions:
  device_name: "vindriktning"
  name: "vindriktning"  
  
esphome:
  name: '${device_name}'
  name_add_mac_suffix: true
  comment: '${device_description}'
  project:
    name: "huizebruin.Huizebruin-projecten_${device_name}"
    version: "${project_version}"
  min_version: 2024.12.0

esp8266:
  board:  d1_mini
  restore_from_flash: true

logger:
  level: INFO

dashboard_import:
  package_import_url: github://huizebruin/Huizebruin-projecten/docs/source/esphome/vindriktning.yaml

packages:
  remote_package:
    url: https://github.com/huizebruin/Huizebruin-projecten
    ref: main
    files:
      - docs/source/esphome/package/vindriktning.yaml
      - docs/source/esphome/package/basis_settings.yaml
    refresh: 0d