# Zoutlevel 
#
# a simple ESPHome integration to make an zoutlevel
# © Huizebruin.nl
#
substitutions:
  device_name: "zoutlevel"
  name: "zoutlevel"
esphome:
  name: '${device_name}'
  name_add_mac_suffix: true
  comment: '${device_description}'
  project:
    name: "huizebruin-projecten.${device_name}"
    version: "${project_version}"
  min_version: 2024.12.0

esp8266:
  board:  d1_mini

logger:
  level: INFO

dashboard_import:
  package_import_url: github://huizebruin/huizebruin-projecten/esphome/zout_level_sensor.yaml

packages:
  remote_package:
    url: https://github.com/huizebruin/huizebruin-projecten
    ref: main
    files:
      - esphome/package/zoutlevel.yaml
      - esphome/package/basis.yaml
    refresh: 0d