name: Build
# Build the ESPHome firmwares for the Huizebruin-projecten project.
on:
  push:
    branches:
      - main
  #pull_request:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: Build firmware 🛠️
    uses: esphome/workflows/.github/workflows/build.yml@main
    with:
      files: |
        esphome/vindriktning.yaml
        esphome/bluetoothproxy.yaml

        
      esphome-version: 2024.12.2
      release-url: "https://github.com/huizebruin/Huizebruin-projecten/releases"
      release-summary: "** Check the release notes for more information. **"

  consolidate:
    name: Consolidate firmwares 🚀
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4.2.2
      - name: Download built firmwares
        uses: actions/download-artifact@v4.1.8
        with:
          path: firmwares
      - name: Remove intermediate version folder
        run: |-
          for d in firmwares/*/*; do
            if [ -d "$d" ]; then
              mv $d/* $d/../
              rm -rf $d
            fi
          done
      - name: Copy files
        run: |-
          mkdir output
          cp -R docs/source/flashing/* output/
          cp -R firmwares/* output/
      - name: Copy manifest files to root and modify paths # This is required so that older firmwares can update to newer firmwares with new manifest paths
        run: |-
          for device in firmwares/*; do
            device=$(basename $device)
            jq --arg device "$device" \
                '.builds[].ota.path |= $device + "/" + . | (.builds[].parts // [])[].path |= $device + "/" + .' \
                firmwares/$device/manifest.json > output/$device-manifest.json
          done
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: output    
      

